### ISSUE TITLE
Black Screen Error

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [Unzor/jsvm#1]
so ,  i was testing my Windows 3.0 Live Floppy Disk (that is MS-DOS 6.22 1.44M Floppy)
it stuck on black screen
![image](https://user-images.githubusercontent.com/71384075/125192319-e0bcab00-e264-11eb-8537-5114e110f4e0.png)

**Comment by Unzor** [comment]
Change the setting to Floppy/Hard Disk, wait for it to load, or check the console. If there is an error saying “Unknown floppy size” then it probably means you have the wrong setting or file extension.

**Comment by Siddhant-Mashalkar** [comment]
in console, it just says that request is blocked by CORS Policy
if you want to try if the floppy disk works on jsvm or not, here is link : https://archive.org/details/windows-3.0-ramdisk-floppy

**Comment by Unzor** [comment]
You will have to upload the URL to your own site. Sorry about that, but it’s impossible to get the floppy disk image from the URL unless you use NodeJS to get the URL without CORS.

**Comment by Siddhant-Mashalkar** [comment]
ok

**Comment by Siddhant-Mashalkar** [comment]
lol it froze at "Starting MS-DOS"
![image](https://user-images.githubusercontent.com/71384075/125390261-3194e680-e3c0-11eb-9079-f62d06783dee.png)

**Comment by Siddhant-Mashalkar** [comment]
and, i tried WIN203.img (Windows 2.03 Floppy Disk i made) , the screen resolution was too big after MS-DOS Executive Started
![image](https://user-images.githubusercontent.com/71384075/125392278-7ec68780-e3c3-11eb-82da-f47ab71c74e8.png)

**Comment by Unzor** [comment]
The resolution is not really a problem at all, you can set the size by using transform: translate(-PERCENTAGE%, -PERCENTAGE%). However, the boot up being stopped on MS-DOS probably means that something went wrong while visualizing the file, and it is not yet fixable.

**Comment by Siddhant-Mashalkar** [comment]
here is console log
![image](https://user-images.githubusercontent.com/71384075/125475373-66621acc-c471-45cf-97b4-33249786374f.png)

**Comment by Unzor** [comment]
Yeah, that probably means there was a problem visualizing the VM.

**Comment by Siddhant-Mashalkar** [comment]
this is With EMM386
![image](https://user-images.githubusercontent.com/71384075/125476907-f808a3e4-9ce1-4f32-96dc-9fed23a21b10.png)

**Comment by Unzor** [comment]
Okay. I am closing this issue, but if you have anything else, just comment something here.
