### ISSUE TITLE
MS-DOS: VM Crashes if EMM386 is loaded in CONFIG.SYS

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [Unzor/jsvm#2]
i have some issues in MS-DOS
i have a MS-DOS Bootdisk File 
in config.sys, it loads EMM386.EXE 
but when it says "Microsoft Expanded Memory Manager", vm freezes and crashes, why?

**Comment by Unzor** [comment]
Maybe the code panicked because of the bootdisk file. Maybe try a new one or use a new OS.

**Comment by Siddhant-Mashalkar** [comment]
okay
