### ISSUE TITLE
many issues with JsVM

### ISSUE THREAD

**Issue by Siddhant-Mashalkar** [Unzor/jsvm#3]
so, i was trying Win95 custom bootable setup cd+unformatted blank hdd image
when it booted from cd, the cd rom driver i used doesn't works
and Fdisk says "No Fixed Disks Present" even if i added the c.img file in vm-instance
why?
![image](https://user-images.githubusercontent.com/71384075/126743723-7ec819d1-0614-47f9-9436-8f9705543d4b.png)

**Comment by Unzor** [comment]
I have no idea how to fix this, but instead, if you don't want to do the installation part, then I suggest downloading this:
https://img-un.glitch.me/win_95.bin
then using it in a VM instance as a state.

**Comment by Siddhant-Mashalkar** [comment]
the issue is: i try VM-Instance (Windows 95 custom bootable cd as iso) + Blank Unformatted HDD created using Bximage as Hard Disk
i think JsVm ignores the hdd line
